<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

/** @var \Hatimeria\GtmPro\Block\Tag $block */
// @codingStandardsIgnoreFile
?>
<div x-data>
    <script>
        function loadGTM() {
            var w = window;
            var d = document;
            var s = 'script';
            var l = 'dataLayer';
            var i = '<?= $block->getContainerId() ?>';
            w[l] = w[l] || [];
            w[l].push({
                'gtm.start': new Date().getTime(),
                event: 'gtm.js',
            });
            var f = d.getElementsByTagName(s)[0],
                j = d.createElement(s),
                dl = l != 'dataLayer' ? '&l=' + l : '';
            j.async = true;
            j.src = 'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
            f.parentNode.insertBefore(j, f);
        }
        loadGTM();
    </script>
</div>
