<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

/** @var \Hatimeria\GtmPro\Block\Event\Form $block */
// @codingStandardsIgnoreFile
?>
<script>
    'use strict';
    window.addEventListener('DOMContentLoaded', () => {
        var pushStep = init();
        pushStep.pushStep();
    });
    function init() {
        return {
            formData: '<?= json_encode($block->getFormData()) ?>' ?? [],
            pushStep() {
                window.dataLayer = window.dataLayer || [];
                var formData = JSON.parse(this.formData);
                Object.values(formData).forEach((data, index) => {
                    if (document.querySelector('#' + data.form_id) && document.querySelector('#' + data.form_id).length) {
                        document.querySelectorAll('#' + data.form_id).forEach(function(element) {
                            element.setAttribute('x-data', "{email:''}");
                        });
                        data.form_field_ids.forEach((fieldId) => {
                            if (document.querySelectorAll('#' + data.form_id + ' #' + fieldId).length) {
                                document.querySelector('#' + data.form_id + ' #' + fieldId).classList.add('trackfield');
                                document.querySelector('#' + data.form_id + ' #' + fieldId).setAttribute('x-model', `${data.event_name}_${fieldId}`);
                            }
                        });
                        var form = document.querySelector('#' + data.form_id);
                        form.addEventListener('submit', event => {
                            this.submitForm(event);
                        });
                    }
                });
            },
            submitForm(event) {
                event.preventDefault();
                var data = {};
                data.event = event.target.getAttribute('x-bind:data-eventname');
                event.target.querySelectorAll('.trackfield').forEach((obj) => {
                    data[obj.getAttribute('id')] = this[`${data.event_name}_${fieldId}`];
                });
                window.dataLayer = window.dataLayer || [];
                window.dataLayer.push(data);
            },
        }
    }
</script>
